const ROLES = {
  EMPLOYEE: "EMPLOYEE",
  MANAGER: "MANAGER",
  FINANCE: "FINANCE",
  ADMIN: "ADMIN"
};

const EXPENSE_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  MANAGER_APPROVED: "MANAGER_APPROVED",
  FINANCE_APPROVED: "FINANCE_APPROVED",
  PAID: "PAID",
  REJECTED: "REJECTED"
};

module.exports = { ROLES, EXPENSE_STATUS };
